org.gradle.jvmargs=-Xmx2048M
loom.ignoreDependencyLoomVersionValidation=true
# Mod
enabled_platforms=fabric
mod_id=envelope
archives_name=envelope
mod_name=Envelope [Unofficial Port]
mod_version=0.2.1
mod_release_type=release
mod_license=GPLv3
maven_group=io.github.mortuusars.envelope
mod_authors=gingermat, original authors
mod_description=Letters and Packages. And Pigeons to deliver them.
mod_page=https://modrinth.com/project/envelope-unofficial-port
mod_github=https://github.com/gingermat24/Envelope-1.21.11-Unofficial-Port
mod_issues=https://github.com/gingermat24/Envelope-1.21.11-Unofficial-Port/issues
mod_curseforge_project_id=1281170
mod_modrinth_project_id=envelope-unofficial-port
# Minecraft
minecraft_version=1.21.11
supported_minecraft_versions=1.21.11
# Fabric
fabric_loader_version=0.19.5
fabric_api_version=0.141.6+1.21.11
# Dependencies
forge_config_api_port_version=21.11.1
jei_version=27.44.0.105